### ISSUE TITLE
Support for Raven 4

### ISSUE THREAD

**Issue by JudahGabriel** [FriendlyAgent/RavenDB.AspNetCore.DependencyInjection#2]
For RavenDB 4+, the code will need to change to support client certificates. Would you accept a PR for this?

**Comment by xinix00** [comment]
Yes he will

**Comment by FriendlyAgent** [comment]
Sure, no problem. I would gladly accept the PR.

**Comment by JudahGabriel** [comment]
OK. Keep in mind, going to Raven 4 is a breaking change. (Raven 4 is not compatible with the Raven 3 API.) I'll submit a PR for this today.

**Comment by JudahGabriel** [comment]
Oh, I see it's already on Raven 4 release candidate. I'll just bump it up to the latest, make sure we support client certs, and submit a PR.

**Comment by JudahGabriel** [comment]
Issued a PR https://github.com/FriendlyAgent/RavenDB.AspNetCore.DependencyInjection/pull/4
